INSERT INTO fixtures VALUES (1,
'Collingwood','Fremantle', 
'GWS GIANTS','Sydney Swans', 
'Gold Coast SUNS','Richmond', 
'Carlton','Port Adelaide', 
'Geelong Cats','Adelaide Crows', 
'North Melbourne','Essendon', 
'Hawthorn','Brisbane Lions', 
'St Kilda','Melbourne', 
'West Coast Eagles','Western Bulldogs'); 
INSERT INTO fixtures VALUES (2,
'Richmond','Carlton', 
'Essendon','Hawthorn', 
'St Kilda','GWS GIANTS', 
'Port Adelaide','Adelaide Crows', 
'Sydney Swans','Collingwood', 
'Fremantle','Gold Coast SUNS', 
'Brisbane Lions','Geelong Cats', 
'Melbourne','West Coast Eagles', 
'Western Bulldogs','North Melbourne'); 
INSERT INTO fixtures VALUES (3,
'Hawthorn','Fremantle', 
'Western Bulldogs','Richmond', 
'Adelaide Crows','Sydney Swans', 
'Gold Coast SUNS','Brisbane Lions', 
'Collingwood','Geelong Cats', 
'West Coast Eagles','St Kilda', 
'GWS GIANTS','Melbourne', 
'North Melbourne','Port Adelaide', 
'Essendon','Carlton'); 
INSERT INTO fixtures VALUES (4,
'Richmond','Collingwood', 
'Carlton','Melbourne', 
'Port Adelaide','Brisbane Lions', 
'GWS GIANTS','Western Bulldogs', 
'Gold Coast SUNS','Hawthorn', 
'Geelong Cats','West Coast Eagles', 
'Sydney Swans','North Melbourne', 
'St Kilda','Adelaide Crows', 
'Fremantle','Essendon'); 
INSERT INTO fixtures VALUES (5,
'Brisbane Lions','Richmond', 
'Collingwood','North Melbourne', 
'Sydney Swans','Fremantle', 
'Essendon','St Kilda', 
'West Coast Eagles','Port Adelaide', 
'Adelaide Crows','GWS GIANTS', 
'Melbourne','Gold Coast SUNS', 
'Western Bulldogs','Carlton', 
'Geelong Cats','Hawthorn'); 
INSERT INTO fixtures VALUES (6,
'Collingwood','Essendon', 
'St Kilda','Brisbane Lions', 
'Fremantle','North Melbourne', 
'Gold Coast SUNS','GWS GIANTS', 
'Carlton','West Coast Eagles', 
'Melbourne','Sydney Swans', 
'Western Bulldogs','Adelaide Crows', 
'Richmond','Hawthorn', 
'Port Adelaide','Geelong Cats'); 
INSERT INTO fixtures VALUES (7,
'Carlton','Collingwood', 
'Hawthorn','St Kilda', 
'GWS GIANTS','Port Adelaide', 
'Adelaide Crows','Melbourne', 
'Essendon','Western Bulldogs', 
'Brisbane Lions','Sydney Swans', 
'North Melbourne','Gold Coast SUNS', 
'Geelong Cats','Richmond', 
'West Coast Eagles','Fremantle'); 
INSERT INTO fixtures VALUES (8,
'Sydney Swans','Geelong Cats', 
'St Kilda','Collingwood', 
'Melbourne','Port Adelaide', 
'Brisbane Lions','Carlton', 
'Essendon','Richmond', 
'Adelaide Crows','Gold Coast SUNS', 
'Western Bulldogs','Fremantle', 
'Hawthorn','GWS GIANTS', 
'West Coast Eagles','North Melbourne'); 
INSERT INTO fixtures VALUES (9,
'Geelong Cats','Carlton', 
'Hawthorn','West Coast Eagles', 
'Port Adelaide','St Kilda', 
'GWS GIANTS','Essendon', 
'Western Bulldogs','Brisbane Lions', 
'Gold Coast SUNS','Sydney Swans', 
'Fremantle','Adelaide Crows', 
'North Melbourne','Richmond', 
'Melbourne','Collingwood'); 
INSERT INTO fixtures VALUES (10,
'Carlton','Hawthorn', 
'Richmond','Fremantle', 
'Sydney Swans','Port Adelaide', 
'West Coast Eagles','Gold Coast SUNS', 
'Adelaide Crows','North Melbourne', 
'Brisbane Lions','GWS GIANTS', 
'Geelong Cats','St Kilda', 
'Collingwood','Western Bulldogs', 
'Essendon','Melbourne'); 
INSERT INTO fixtures VALUES (11,
'Richmond','Sydney Swans', 
'Port Adelaide','Western Bulldogs', 
'Hawthorn','Collingwood', 
'Gold Coast SUNS','Geelong Cats', 
'Essendon','Adelaide Crows', 
'Fremantle','Brisbane Lions', 
'GWS GIANTS','Carlton', 
'St Kilda','West Coast Eagles', 
'Melbourne','North Melbourne'); 
INSERT INTO fixtures VALUES (12,
'Geelong Cats','Essendon', 
'Hawthorn','Gold Coast SUNS', 
'St Kilda','Richmond', 
'Fremantle','West Coast Eagles', 
'Brisbane Lions','North Melbourne', 
'Sydney Swans','GWS GIANTS', 
'Western Bulldogs','Melbourne', 
'Adelaide Crows','Port Adelaide', 
'Collingwood','Carlton'); 
INSERT INTO fixtures VALUES (13,
'North Melbourne','Hawthorn', 
'Richmond','Brisbane Lions', 
'GWS GIANTS','Adelaide Crows', 
'Gold Coast SUNS','Collingwood', 
'Port Adelaide','Essendon', 
'Melbourne','Fremantle', 
'Carlton','St Kilda', 
'West Coast Eagles','Sydney Swans', 
'Geelong Cats','Western Bulldogs'); 
INSERT INTO fixtures VALUES (14,
'Adelaide Crows','Hawthorn', 
'Melbourne','Geelong Cats', 
'North Melbourne','St Kilda', 
'Western Bulldogs','Gold Coast SUNS', 
'Sydney Swans','Carlton', 
'Brisbane Lions','West Coast Eagles', 
'Richmond','Port Adelaide', 
'Essendon','Collingwood', 
'Fremantle','GWS GIANTS'); 
INSERT INTO fixtures VALUES (15,
'Carlton','North Melbourne', 
'St Kilda','Fremantle', 
'GWS GIANTS','Geelong Cats', 
'Port Adelaide','Melbourne', 
'Western Bulldogs','Essendon', 
'West Coast Eagles','Richmond', 
'Brisbane Lions','Gold Coast SUNS', 
'Hawthorn','Sydney Swans', 
'Collingwood','Adelaide Crows'); 
INSERT INTO fixtures VALUES (16,
'Fremantle','Carlton', 
'Sydney Swans','Essendon', 
'Adelaide Crows','West Coast Eagles', 
'Richmond','GWS GIANTS', 
'North Melbourne','Geelong Cats', 
'Gold Coast SUNS','St Kilda', 
'Melbourne','Brisbane Lions', 
'Hawthorn','Western Bulldogs', 
'Collingwood','Port Adelaide'); 
INSERT INTO fixtures VALUES (17,
'Richmond','Essendon', 
'GWS GIANTS','North Melbourne', 
'Carlton','Gold Coast SUNS', 
'Hawthorn','Melbourne', 
'Geelong Cats','Fremantle', 
'Port Adelaide','Sydney Swans', 
'Brisbane Lions','Adelaide Crows', 
'St Kilda','Western Bulldogs', 
'West Coast Eagles','Collingwood'); 
INSERT INTO fixtures VALUES (18,
'Carlton','Geelong Cats', 
'Sydney Swans','St Kilda', 
'Gold Coast SUNS','Port Adelaide', 
'Essendon','West Coast Eagles', 
'Adelaide Crows','Richmond', 
'Collingwood','Brisbane Lions', 
'North Melbourne','Western Bulldogs', 
'Melbourne','GWS GIANTS', 
'Fremantle','Hawthorn'); 
INSERT INTO fixtures VALUES (19,
'Port Adelaide','Carlton', 
'North Melbourne','Adelaide Crows', 
'Essendon','Gold Coast SUNS', 
'GWS GIANTS','Collingwood', 
'Hawthorn','Geelong Cats', 
'West Coast Eagles','Melbourne', 
'Brisbane Lions','Fremantle', 
'Western Bulldogs','Sydney Swans', 
'Richmond','St Kilda'); 
INSERT INTO fixtures VALUES (20,
'Carlton','Essendon', 
'Geelong Cats','Brisbane Lions', 
'North Melbourne','Melbourne', 
'Adelaide Crows','St Kilda', 
'Collingwood','Hawthorn', 
'Fremantle','Port Adelaide', 
'Gold Coast SUNS','West Coast Eagles', 
'Sydney Swans','Richmond', 
'Western Bulldogs','GWS GIANTS'); 
