INSERT INTO teams
VALUES ('Adelaide Crows', 'SA'), 
 ('Brisbane Lions', 'QLD'), 
 ('Carlton', 'VIC'),
 ('Collingwood', 'VIC'),
 ('Essendon', 'VIC'),
 ('Fremantle', 'WA'),
 ('Geelong Cats', 'VIC'),
 ('Gold Coast SUNS', 'QLD'),
 ('GWS GIANTS', 'NSW'),
 ('Hawthorn', 'VIC'),
 ('Melbourne', 'VIC'),
 ('North Melbourne', 'VIC'),
 ('Port Adelaide', 'SA'),
 ('Richmond', 'VIC'),
 ('St Kilda', 'VIC'),
 ('Sydney Swans', 'NSW'),
 ('West Coast Eagles', 'WA'),
 ('Western Bulldogs', 'VIC');
